function strip(s=''){return String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim()}
async function get(url,timeout=12000){const c=new AbortController();const t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,headers:{'user-agent':'Mozilla/5.0 (Linux; Android 16; Mobile) AppleWebKit/537.36 Chrome/125 Mobile Safari/537.36','accept-language':'ko-KR,ko;q=0.9,en;q=0.7','accept':'text/html,application/xhtml+xml,*/*'}});return{status:r.status,text:await r.text(),type:r.headers.get('content-type'),url:r.url}}finally{clearTimeout(t)}}
function allLinks(html){const out=[];for(const m of html.matchAll(/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){const href=m[1],title=strip(m[2]);if(href&&title)out.push({title:title.slice(0,180),href:href.slice(0,700)})}return out}
(async()=>{
 const u='https://scienceon.kisti.re.kr/srch/selectPORSrchPatent.do?cn=KOR1020200175557';
 try{
   const r=await get(u);const txt=strip(r.text);const links=allLinks(r.text).filter(x=>/박상훈|세메스|특허|invent|author|search|srch/i.test(x.title+' '+x.href)).slice(0,80);const forms=[...r.text.matchAll(/<form[\s\S]*?<\/form>/gi)].slice(0,8).map(m=>strip(m[0]).slice(0,1200));const inputs=[...r.text.matchAll(/<(?:input|select)[^>]+>/gi)].slice(0,120).map(m=>m[0]).filter(x=>/name=|id=/i.test(x)).slice(0,80);console.log('[DEBUG-SCIENCEON]',JSON.stringify({status:r.status,type:r.type,len:r.text.length,hits:{park:(txt.match(/박상훈/g)||[]).length,semes:(txt.match(/세메스/g)||[]).length},links,forms,inputs,context:txt.slice(Math.max(0,txt.indexOf('박상훈')-1200),txt.indexOf('박상훈')+2400)}))
 }catch(e){console.log('[DEBUG-SCIENCEON-ERR]',e.message)}
 const queries=['"박상훈" "세메스"','"박상훈" "세메스" 특허','"박상훈" "세메스" 본딩','"박상훈" "세메스" 잉크젯','"박상훈" "세메스" 프린팅','"박상훈" "세메스" 기판'];
 for(const q of queries){try{const r=await get(`https://search.naver.com/search.naver?where=web&query=${encodeURIComponent(q)}`);const arr=allLinks(r.text).filter(x=>/scienceon\.kisti\.re\.kr.*Patent|patents\.google\.com/i.test(x.href));console.log('[DEBUG-NAVER-PATENTS]',JSON.stringify({q,count:arr.length,links:arr.slice(0,30)}))}catch(e){console.log('[DEBUG-NAVER-ERR]',q,e.message)}}
})().catch(e=>console.error('[DEBUG-FATAL]',e));
