const http=require('http');
const fs=require('fs');
const path=require('path');
const {URL}=require('url');
const PORT=process.env.PORT||10000,PUBLIC=path.join(__dirname,'public'),MAX_BODY=64*1024;

function clean(v,max=180){return String(v||'').trim().replace(/[\u0000-\u001f]/g,' ').slice(0,max)}
function decode(s=''){return String(s).replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&#x27;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&nbsp;/g,' ').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(+n))}
function strip(s=''){return decode(String(s).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim())}
function domainOf(u=''){try{return new URL(u).hostname.replace(/^www\./,'')}catch{return''}}
function yearOf(r){if(r.year)return r.year;const m=`${r.title||''} ${r.snippet||''}`.match(/\b(20\d{2}|19\d{2})\b/);return m?+m[1]:null}
async function fetchText(url,opts={},timeout=9000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{...opts,signal:c.signal,redirect:'follow',headers:{'user-agent':'Mozilla/5.0 (Linux; Android 16; Mobile) AppleWebKit/537.36 Chrome/125 Mobile Safari/537.36','accept-language':'ko-KR,ko;q=0.9,en;q=0.7','accept':'text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8',...(opts.headers||{})}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text()}finally{clearTimeout(t)}}

function normalizeHref(h=''){h=decode(h);if(h.startsWith('//'))h='https:'+h;return h}
function isUsefulUrl(u=''){return /^https?:\/\//i.test(u)&&!/(search\.naver\.com|m\.search\.naver\.com|help\.naver\.com|nid\.naver\.com)/i.test(u)}
function parseNaverHtml(html,sourceQuery=''){const out=[],seen=new Set(),re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))&&out.length<80){const url=normalizeHref(m[1]);if(!isUsefulUrl(url))continue;const key=url.replace(/[?#].*$/,'');if(seen.has(key))continue;const title=strip(m[2]);if(!title||title.length<2)continue;const around=strip(html.slice(Math.max(0,m.index-1000),Math.min(html.length,re.lastIndex+2200)));seen.add(key);out.push({title:title.slice(0,320),url,snippet:around.slice(0,1600),source:'naver-html',sourceQuery})}return out}
async function naverHtmlSearch(query,pages=2){const batches=[];for(let p=0;p<pages;p++){const start=1+p*10;try{const html=await fetchText(`https://search.naver.com/search.naver?where=web&query=${encodeURIComponent(query)}&start=${start}`,{},9000);batches.push(parseNaverHtml(html,query))}catch{}}return batches.flat()}

function contextWindow(text,terms=[]){const low=text.toLowerCase();let idx=-1;for(const t of terms.filter(Boolean)){const i=low.indexOf(t.toLowerCase());if(i>=0){idx=i;break}}if(idx<0)return text.slice(0,2200);return text.slice(Math.max(0,idx-900),Math.min(text.length,idx+1800))}
async function enrichScienceOn(r,name,company){if(!/scienceon\.kisti\.re\.kr/i.test(r.url))return r;try{const html=await fetchText(r.url,{},9000);const body=strip(html);const tm=html.match(/<meta[^>]+(?:property|name)=["'](?:og:title|title)["'][^>]+content=["']([^"']+)["']/i)||html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);const title=tm?strip(tm[1]):r.title;const snippet=contextWindow(body,[name,company,'발명자','출원인']);const m=body.match(/\b(20\d{2}|19\d{2})\b/);return{...r,title:title||r.title,snippet,source:/Patent/i.test(r.url)||/특허|발명자|출원인/.test(body)?'scienceon-patent':'scienceon',year:m?+m[1]:null}}catch{return r}}
async function enrichResults(rows,name,company){const selected=rows.slice(0,45),out=[];for(let i=0;i<selected.length;i+=6){const chunk=selected.slice(i,i+6);out.push(...await Promise.all(chunk.map(r=>enrichScienceOn(r,name,company))))}return out}

async function crossrefSearch(name,h){try{const q=[name,h.company,h.school,h.role].filter(Boolean).join(' '),txt=await fetchText(`https://api.crossref.org/works?query.bibliographic=${encodeURIComponent(q)}&rows=6&select=DOI,title,author,published,URL,publisher`,{headers:{accept:'application/json'}},7000),j=JSON.parse(txt);return(j.message?.items||[]).map(x=>{const year=x.published?.['date-parts']?.[0]?.[0]||null,authors=(x.author||[]).map(a=>[a.given,a.family].filter(Boolean).join(' ')).join(', ');return{title:(x.title||[])[0]||'학술 자료',url:x.URL||`https://doi.org/${x.DOI}`,snippet:[authors,x.publisher,year].filter(Boolean).join(' · '),year,source:'academic'}})}catch{return[]}}
async function naverApiSearch(q){const id=process.env.NAVER_CLIENT_ID,secret=process.env.NAVER_CLIENT_SECRET;if(!id||!secret)return[];const headers={'X-Naver-Client-Id':id,'X-Naver-Client-Secret':secret},kinds=[['webkr','naver-web'],['blog','naver-blog'],['cafearticle','naver-cafe'],['news','naver-news']];const b=await Promise.all(kinds.map(async([k,s])=>{try{const t=await fetchText(`https://openapi.naver.com/v1/search/${k}.json?query=${encodeURIComponent(q)}&display=10&sort=sim`,{headers},7000);return(JSON.parse(t).items||[]).map(x=>({title:strip(x.title),url:x.link||x.originallink,snippet:strip(x.description),source:s,sourceQuery:q}))}catch{return[]}}));return b.flat()}

function categoryOf(r){const d=domainOf(r.url).toLowerCase(),t=`${r.title||''} ${r.snippet||''}`.toLowerCase();if(r.source==='scienceon-patent'||d.includes('patents.google')||d.includes('kipris')||(/scienceon/.test(d)&&/특허|발명자|출원인/.test(t)))return'patent';if(/instagram\.com|facebook\.com|threads\.net|youtube\.com|youtu\.be/.test(d))return'social';if(/blog\.naver\.com|tistory\.com|brunch\.co\.kr|post\.naver\.com/.test(d)||/naver-blog/.test(r.source||''))return'blog';if(/cafe\.naver\.com|cafe\.daum\.net/.test(d)||/naver-cafe/.test(r.source||''))return'community';if(d.includes('linkedin.com'))return'career';if(d.includes('github.com'))return'developer';if(r.source==='academic'||d.includes('doi.org'))return'academic';if(/news|기사|뉴스/.test(t)||/naver-news/.test(r.source||''))return'news';return'web'}
function confidence(r,h){const hay=`${r.title||''} ${r.snippet||''}`.toLowerCase(),q=(r.sourceQuery||'').toLowerCase();let s=16;const name=h.name?.toLowerCase(),company=h.company?.toLowerCase();if(name&&hay.includes(name))s+=32;if(company&&hay.includes(company))s+=25;if(name&&company&&q.includes(name)&&q.includes(company))s+=8;if(h.school&&hay.includes(h.school.toLowerCase()))s+=14;if(h.role&&hay.includes(h.role.toLowerCase()))s+=10;if(h.region&&hay.includes(h.region.toLowerCase()))s+=6;if(h.nickname&&hay.includes(h.nickname.toLowerCase()))s+=16;if(categoryOf(r)==='patent'&&name&&company&&(hay.includes(name)||q.includes(name))&&(hay.includes(company)||q.includes(company)))s+=20;return Math.min(98,s)}
const INTERESTS=[['기술·엔지니어링',['wafer','bonding','chuck','semiconductor','반도체','엔지니어','설계','장비','특허','patent','기판','본딩','printing','inkjet','프린팅','잉크젯']],['소프트웨어·AI',['github','developer','software','python','javascript','llm','코딩','개발']],['투자·경제',['주식','투자','etf','stock','finance','경제','부동산']],['여행',['여행','travel','호텔','항공','trip','관광']],['음식·카페',['맛집','카페','coffee','restaurant']],['자동차',['자동차','car','vehicle','드라이브']],['반려동물',['강아지','고양이','반려','dog','cat','pet']],['문화·콘텐츠',['영화','드라마','공연','음악','책','movie','music','book']]];
function inferPersona(rows,h){const text=rows.map(r=>`${r.title} ${r.snippet}`).join(' ').toLowerCase(),interests=INTERESTS.map(([label,terms])=>{const hits=terms.reduce((n,x)=>n+(text.split(x).length-1),0);return{label,hits,confidence:Math.min(95,48+hits*6)}}).filter(x=>x.hits).sort((a,b)=>b.hits-a.hits).slice(0,5),cats=rows.reduce((m,r)=>(m[categoryOf(r)]=(m[categoryOf(r)]||0)+1,m),{}),styles=[];if((cats.patent||0)+(cats.academic||0)>=2)styles.push({label:'전문성 중심',confidence:Math.min(95,64+((cats.patent||0)+(cats.academic||0))*5),why:'특허·연구 기록이 반복적으로 발견됨'});if((cats.blog||0)+(cats.social||0)>=2)styles.push({label:'기록·공유형',confidence:Math.min(90,56+((cats.blog||0)+(cats.social||0))*5),why:'블로그·SNS 공개 활동이 반복적으로 발견됨'});if(/비교|분석|리뷰|후기|정리|가이드/.test(text))styles.push({label:'분석·비교형',confidence:70,why:'비교·분석형 콘텐츠가 반복됨'});let occupation=h.role||'';if(!occupation&&/wafer|bonding|semiconductor|반도체|엔지니어|설계|장비|특허|기판|printing|inkjet/.test(text))occupation='기술·엔지니어링 종사 가능성';else if(!occupation&&/developer|software|github|개발자/.test(text))occupation='소프트웨어·개발 종사 가능성';return{occupation:occupation||'직업을 충분히 추정하기 어려움',interests,styles:styles.slice(0,3)}}
function buildReport(h,results){const enriched=results.map(r=>({...r,category:categoryOf(r),confidence:confidence(r,h),domain:domainOf(r.url),year:yearOf(r)})),likely=enriched.filter(r=>r.confidence>=55),cats=[...new Set(likely.map(r=>r.category))],domains=[...new Set(likely.map(r=>r.domain).filter(Boolean))],hintCount=['company','school','role','region','nickname','social','keyword','ageBand'].filter(k=>h[k]).length,score=Math.min(96,Math.round(15+likely.length*3+cats.length*6+domains.length*2+hintCount*2)),match=Math.min(97,Math.round(42+hintCount*5+Math.min(likely.length,12)*3)),persona=inferPersona(likely,h),top=persona.interests.slice(0,3).map(x=>x.label),pc=likely.filter(r=>r.category==='patent').length;let narrative=`공개 인터넷에서 ${h.name}과 연결 가능성이 높은 흔적 ${likely.length}건을 찾았습니다.`;if(h.company)narrative+=` ${h.company} 관련 정보와 교차해 동명이인을 줄였습니다.`;if(pc)narrative+=` 특허·발명 기록 ${pc}건이 본인 후보와 연결됩니다.`;if(persona.occupation!=='직업을 충분히 추정하기 어려움')narrative+=` 공개 기록만 보면 ‘${persona.occupation}’이 높습니다.`;if(top.length)narrative+=` 반복되는 관심 주제는 ${top.join(', ')}입니다.`;const grouped={};for(const r of likely.sort((a,b)=>b.confidence-a.confidence))(grouped[r.category]||=[]).push(r);const timeline=likely.filter(r=>r.year).sort((a,b)=>a.year-b.year).slice(0,18).map(r=>({year:r.year,title:r.title,category:r.category,confidence:r.confidence}));return{score,confidence:match,narrative,keywords:top,persona,grouped,timeline,stats:{likely:likely.length,total:enriched.length,domains:domains.length,categories:cats.length,patents:pc},sources:{naverHtml:true,scienceOn:true,naverApi:Boolean(process.env.NAVER_CLIENT_ID&&process.env.NAVER_CLIENT_SECRET),publicWeb:true}}}
async function scan(input){if(input.selfAudit!=='yes')throw new Error('본인 또는 본인의 동의를 받은 검색만 이용할 수 있습니다.');const name=clean(input.name,80);if(!name)throw new Error('이름은 필수입니다.');const h={name,ageBand:clean(input.ageBand,20),company:clean(input.company,100),school:clean(input.school,100),role:clean(input.role,100),region:clean(input.region,80),nickname:clean(input.nickname,80),social:clean(input.social,180),github:clean(input.github,50),keyword:clean(input.keyword,100)};const strict=[name,h.company].filter(Boolean).map(x=>`"${x}"`).join(' '),core=[name,h.company,h.school,h.role,h.region,h.nickname].filter(Boolean).join(' ');const queries=[strict,`${strict} 특허`,`${strict} 발명자`,`${strict} site:scienceon.kisti.re.kr`,`${strict} site:patents.google.com`,`${strict} 엔지니어`,`${strict} site:linkedin.com`,`${strict} site:blog.naver.com`,`${strict} site:instagram.com`,`${strict} site:facebook.com`].filter(Boolean);if(h.keyword)queries.unshift(`${strict} "${h.keyword}"`);if(h.nickname)queries.unshift(`"${name}" "${h.nickname}"`);const jobs=queries.map((q,i)=>naverHtmlSearch(q,i<4?3:1));jobs.push(naverApiSearch(core),crossrefSearch(name,h));const batches=await Promise.all(jobs.map(p=>Promise.resolve(p).catch(()=>[])));let rows=batches.flat();rows=await enrichResults(rows,name,h.company);const seen=new Map();for(const r of rows){if(!r||!r.url)continue;const k=r.url.replace(/[?#].*$/,'');const old=seen.get(k);if(!old||confidence(r,h)>confidence(old,h))seen.set(k,r)}return{input:h,report:buildReport(h,[...seen.values()])}}
function sendJson(res,code,obj){res.writeHead(code,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(obj))}
function serveStatic(res,pn){let f=pn==='/'?'/index.html':pn;f=path.normalize(f).replace(/^\.\.(\/|\\)/,'');const full=path.join(PUBLIC,f);if(!full.startsWith(PUBLIC))return sendJson(res,403,{error:'Forbidden'});fs.readFile(full,(e,d)=>{if(e){res.writeHead(404);return res.end('Not found')}const ext=path.extname(full),types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8'};res.writeHead(200,{'content-type':types[ext]||'application/octet-stream','cache-control':ext==='.html'?'no-cache':'public,max-age=120'});res.end(d)})}
const server=http.createServer((req,res)=>{const u=new URL(req.url,`http://${req.headers.host}`);if(req.method==='GET'&&u.pathname==='/health')return sendJson(res,200,{ok:true,version:'0.6.0'});if(req.method==='GET'&&u.pathname==='/api/selftest'){scan({selfAudit:'yes',name:'박상훈',company:'세메스'}).then(x=>sendJson(res,200,{ok:x.report.stats.patents>=2,stats:x.report.stats,persona:x.report.persona,patents:(x.report.grouped.patent||[]).slice(0,12).map(r=>({title:r.title,url:r.url,confidence:r.confidence,snippet:r.snippet?.slice(0,240)}))})).catch(e=>sendJson(res,500,{ok:false,error:e.message}));return}if(req.method==='POST'&&u.pathname==='/api/scan'){let b='';req.on('data',c=>{b+=c;if(b.length>MAX_BODY)req.destroy()});req.on('end',async()=>{try{sendJson(res,200,await scan(JSON.parse(b||'{}')))}catch(e){sendJson(res,400,{error:e.message||'검색 실패'})}});return}if(req.method==='GET')return serveStatic(res,u.pathname);res.writeHead(405);res.end('Method not allowed')});
if(require.main===module)server.listen(PORT,()=>console.log(`Footprint v0.6 listening on ${PORT}`));
module.exports={clean,parseNaverHtml,categoryOf,confidence,inferPersona,buildReport,scan};
